### ISSUE TITLE
Proofread before publication

### ISSUE THREAD

**Issue by regisb** [regisb/openedx-install#1]
Ping @OmarIthawi :)

**Comment by OmarIthawi** [comment]
Thanks @regisb. Will do!

**Comment by OmarIthawi** [comment]
I think it's useful to provide sane defaults in the `*.*.json` files. I was having fun till I reached those files!

**Comment by regisb** [comment]
Yes, they are tedious... Initially I had sample files with explicit values, but I thought it would be too hard to detect what had to be changed. Maybe we can write an interactive script to ask the user which values they want to use? Something like:

    LMS site name (default: myopenedx.com): pouac.com
    CMS site name (default: myopenedx.com): studio.pouac.com
    ...

But then, users will ask to generate the Nginx files for them... Which is pretty much what the Ansible playbooks do! We need to find a middle ground here. Or make PRs to Open edX to simplify these damn config files;

**Comment by OmarIthawi** [comment]
Yeah, I agree with you @regisb the python files should have the sane defaults!

**Comment by regisb** [comment]
Improving the default JSON files is a different issue, so let me close this for now. Thanks again for your review @OmarIthawi!
