### ISSUE TITLE
python requirement installation

### ISSUE THREAD

**Issue by waikit0624** [regisb/openedx-install#12]
$pip install -r requirements/edx/pre.txt
You must give at least one requirement to install (see "pip help install")

**Comment by regisb** [comment]
Hi, thanks for reporting an issue!
I don't quite understand what problem you are facing. Does the `requirements/edx/pre.txt` file exist? Can you check if it's empty?

**Comment by waikit0624** [comment]
i was following the steps in the guide up until this step , so its empty indeed

________________________________

**Comment by regisb** [comment]
The `pre.txt` file is really not supposed to be empty. It comes with the checkout of `edx-platform`. As we can see, it's not empty in the master branch of the repo: https://github.com/edx/edx-platform/blob/master/requirements/edx/pre.txt
Can you double check which version of edx-platform you have checked out?

**Comment by waikit0624** [comment]
git checkout open-release/ficus.master

i used this . I'm aware that pretty much all the txt.files are empty ... How shall i proceed? remove the empty ones and reclone the right one but i dont have permission to delete the edx-platform or is there another workaround?



________________________________

**Comment by regisb** [comment]
As you can see, the `pre.txt` file is not empty in the `ficus.master` branch : https://github.com/edx/edx-platform/blob/open-release/ficus.master/requirements/edx/pre.txt
It's probably that something has gone wrong during the checkout of edx-platform. I suggest you delete the repo and clone it again.

**Comment by waikit0624** [comment]
noted .. thank you very much


________________________________

**Comment by waikit0624** [comment]
it worked .. Got the correct text files. Thanks




________________________________
