### ISSUE TITLE
Error in cms/production.py

### ISSUE THREAD

**Issue by WolfieZero** [regisb/openedx-install#13]
Is this required in the production file for CMS

https://github.com/regisb/openedx-install/blob/b642e6eb6a3832fb3303488d1ffe26c8b29910be/config/cms/production.py#L7

When I run `./manage.py cms migrate --settings=production` I get an error referencing that key (apologies, I lost the original error). Since removing that line it migrates fine.

**Comment by regisb** [comment]
You are absolutely right.
