### ISSUE TITLE
"paver update_assets lms --settings=development" build failed message

### ISSUE THREAD

**Issue by simpleNslow** [regisb/openedx-install#20]
I've got a message during executing "paver update_assets lms --settings=development"

-----------------------------------------------------------------------------------------------------------------

Captured Task Output:

---------------------

---> pavelib.assets.update_assets
---> pavelib.prereqs.install_node_prereqs
xmodule_assets common/static/xmodule
mkdir_p path('common/static/common/js/vendor')
/bin/cp -rf node_modules/backbone.paginator/lib/backbone.paginator.js common/static/common/js/vendor
/bin/cp -rf node_modules/backbone/backbone.js common/static/common/js/vendor
/bin/cp -rf node_modules/bootstrap/dist/js/bootstrap.js common/static/common/js/vendor
/bin/cp -rf node_modules/hls.js/dist/hls.js common/static/common/js/vendor
/bin/cp -rf node_modules/jquery-migrate/dist/jquery-migrate.js common/static/common/js/vendor
/bin/cp -rf node_modules/jquery.scrollto/jquery.scrollTo.js common/static/common/js/vendor
/bin/cp -rf node_modules/jquery/dist/jquery.js common/static/common/js/vendor
/bin/cp -rf node_modules/moment-timezone/builds/moment-timezone-with-data.js common/static/common/js/vendor
/bin/cp -rf node_modules/moment/min/moment-with-locales.js common/static/common/js/vendor
/bin/cp -rf node_modules/picturefill/dist/picturefill.js common/static/common/js/vendor
/bin/cp -rf node_modules/requirejs/require.js common/static/common/js/vendor
/bin/cp -rf node_modules/tether/dist/js/tether.js common/static/common/js/vendor
/bin/cp -rf node_modules/underscore.string/dist/underscore.string.js common/static/common/js/vendor
/bin/cp -rf node_modules/underscore/underscore.js common/static/common/js/vendor
/bin/cp -rf node_modules/sinon/pkg/sinon.js common/static/common/js/vendor
/bin/cp -rf node_modules/squirejs/src/Squire.js common/static/common/js/vendor
---> pavelib.assets.compile_coffeescript
node_modules/.bin/coffee --compile `find /opt/openedx/edx-platform/lms /opt/openedx/edx-platform/cms /opt/openedx/edx-platform/common -type f -name "*.coffee"`
python manage.py lms --settings=development print_settings STATIC_ROOT --format=value 2>/dev/null

Build failed running pavelib.assets.update_assets: Subprocess return code: 1

-----------------------------------------------------------------------------------------------------------

And When I executed "python manage.py lms --settings=development print_settings STATIC_ROOT --format=value", I got the following error message.

----------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "manage.py", line 111, in <module>
    startup = importlib.import_module(edx_args.startup)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/openedx/edx-platform/lms/startup.py", line 12, in <module>
    settings.INSTALLED_APPS  # pylint: disable=pointless-statement
  File "/opt/openedx/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/opt/openedx/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/openedx/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/openedx/edx-platform/lms/envs/development.py", line 1, in <module>
    from .devstack import *
  File "/opt/openedx/edx-platform/lms/envs/devstack.py", line 6, in <module>
    from .aws import *  # pylint: disable=wildcard-import, unused-wildcard-import
  File "/opt/openedx/edx-platform/lms/envs/aws.py", line 119, in <module>
    ENV_TOKENS = json.load(env_file)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 18 column 3 (char 537)

--------------------------------------------------------------------------------------------------------

**Comment by regisb** [comment]
Hi @simpleNslow! Thanks for taking the time to open this issue!
It appears the lms.env.json file is badly formatted around line 18. Did you manually modify config/openedx/lms.env.json?

**Comment by simpleNslow** [comment]
I left line 18 untouched.
After removing the line, the command has been executed successfully.
Thanks!
