### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by jithinsha** [regisb/openedx-install#21]
Am trying to install open-edx. I found the automated ones as well as i found your instructions as well.
I followed the steps, but got error in two places for building.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
edxapp@openedX:/opt/openedx/edx-platform$ paver update_assets cms --settings=development

Build failed running pavelib.assets.update_assets: Subprocess return code: 1
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

same error for lms as well. but the supervisor list the services.

++++++++++++++++++++++++++++++++++++
One correction required : for cms supervisor, the document is the copy of lms, i manually replaced all lms with cms to get it working
++++++++++++++++++++++++++++++++++++++

My main concern is, How can see the openedx webpage here. 

edx@openedX:/opt/openedx$ sudo supervisorctl status
cms                              RUNNING   pid 27200, uptime 0:00:07
cms:lms_default_1                RUNNING   pid 27176, uptime 0:00:13
cms:lms_high_1                   RUNNING   pid 27175, uptime 0:00:13
cms:lms_high_mem_1               RUNNING   pid 27173, uptime 0:00:13
cms:lms_low_1                    RUNNING   pid 27172, uptime 0:00:13
cms_default_1                    RUNNING   pid 27177, uptime 0:00:13
cms_high_1                       RUNNING   pid 27178, uptime 0:00:13
cms_high_mem_1                   RUNNING   pid 27180, uptime 0:00:13
cms_workers:cms_low_1            RUNNING   pid 27181, uptime 0:00:13
cms_workers:lms_default_1        RUNNING   pid 27186, uptime 0:00:13
cms_workers:lms_high_1           RUNNING   pid 27185, uptime 0:00:13
cms_workers:lms_high_mem_1       RUNNING   pid 27183, uptime 0:00:13
lms                              RUNNING   pid 27250, uptime 0:00:01
lms:lms_default_1                RUNNING   pid 27205, uptime 0:00:05
lms:lms_high_1                   RUNNING   pid 27192, uptime 0:00:09
lms:lms_high_mem_1               RUNNING   pid 27196, uptime 0:00:08
lms:lms_low_1                    RUNNING   pid 27191, uptime 0:00:11
lms_workers:lms_default_1        RUNNING   pid 27187, uptime 0:00:13
lms_workers:lms_high_1           RUNNING   pid 27249, uptime 0:00:01
lms_workers:lms_high_mem_1       STARTING  
lms_workers:lms_low_1            RUNNING   pid 27212, uptime 0:00:03
edx@openedX:/opt/openedx$ 

If you need the config files, i have no issues in forwarding that as well.... 

Kindly help in this...

**Comment by regisb** [comment]
Dear @jithinsha ,
Thanks for pointing out the link error! The correct CMS configuration is: https://github.com/regisb/openedx-install/blob/master/config/supervisor/conf.d/cms.conf

As for your error:
1. Please paste the *complete* error log. 
2. Please indicate the version of edx-platform that you are trying to run.

**Comment by regisb** [comment]
1. The actual error is eaten by the `2> /dev/null`. Please run the following command and paste here the complete output: `python manage.py lms --settings=development print_settings STATIC_ROOT --format=value`
2. Please give the output of the following command in the edx-platform folder: `git log -1`

**Comment by regisb** [comment]
You are missing some requirements: `ImportError: No module named safe_lxml`. Are you sure you did run all the `pip install -r ...` commands? `safe_lxml` should be installed after you install the `local.txt` requirements. Note that the `pip install -r ...` commands must be run from inside the virtualenv, so after you have run `source venv/bin/activate`.

@jithinsha do you have experience with linux administration and python development? If not, I strongly recommend you try the official Open edX install, or running a Bitnami image instead.

**Comment by jithinsha** [comment]
Hi,
Am sure that I do have run all the commands. For a test, i will redo and test once again. Yes am experienced in linux administration, but not that good in python development.

Thanks

**Comment by jithinsha** [comment]
Hi regis,
Yes, this time i was successfully able to run the development stage successfully.
Thanks for the helping hand....

**Comment by regisb** [comment]
Awesome!
