### ISSUE TITLE
Where is the file lms.env.json

### ISSUE THREAD

**Issue by karan1276** [regisb/openedx-install#7]
Awesome work, this manual was much needed. I just want to make sure i am not missing any thing.

In the line
> Edit config/lms/lms.env.json and copy it to /opt/openedx/lms.env.json.

Where is "config/lms/lms.env.json" located ? I don't think the config folder gets cloned, where do i get those config files from?

**Comment by regisb** [comment]
The sample configuration files are stored in *this* repo :) (the opened-install repo)
I guess I'll have to make this more explicit...

**Comment by regisb** [comment]
Here is the config folder: https://github.com/regisb/openedx-install/tree/master/config

**Comment by karan1276** [comment]
Awesome, that should be it :)

**Comment by regisb** [comment]
FYI, I just added links to the config files to make it more explicit that they are located in this repo.
